# Generated by Django 4.2.5 on 2023-09-20 10:41

import currencies.models.currency
import currencies.models.currency_rates
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("currency_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        max_length=5,
                        validators=[
                            currencies.models.currency.CurrencyValidators.validate_abbreviation_uppercase
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "currency_rate_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                (
                    "rate",
                    models.FloatField(
                        db_index=True,
                        validators=[
                            currencies.models.currency_rates.CurrencyRateValidators.validate_currency_rate_value
                        ],
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "db_table": "currency_rates",
                "unique_together": {("currency_rate_id", "currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                (
                    "currency_conversion_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "base_currency_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_currency_rate",
                        to="currencies.currencyrate",
                    ),
                ),
                (
                    "compare_currency_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compare_currency_rate",
                        to="currencies.currencyrate",
                    ),
                ),
            ],
            options={
                "db_table": "currencies_conversion",
            },
        ),
    ]
